version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rent-management-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: rent-management
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rent-management-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rent-management-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/rent-management?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - rent-management-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rent-management-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - rent-management-network

volumes:
  mongodb_data:

networks:
  rent-management-network:
    driver: bridge
